apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-service
  namespace: default
subsets:
  - addresses:
      - ip: 10.244.2.7
    ports:
      - name: postgres
        port: 5432
      - name: metrics
        port: 9187
  - addresses:
      - ip: 10.244.2.8
    ports:
      - name: postgres
        port: 5432
      - name: metrics
        port: 9187
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-primary
  namespace: default
subsets:
  - addresses:
      - ip: 10.244.1.16
    ports:
      - name: postgres
        port: 5432
      - name: metrics
        port: 9187


