apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-service
  namespace: default
subsets:
  - addresses:
      - ip: 10.244.2.7
      - ip: 10.244.2.8
    ports:
      - name: postgres
        port: 5432
      - name: metrics
        port: 9187
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-primary
  namespace: default
subsets:
  - addresses:
      - ip: postgres-0.postgres-primary.default.svc.cluster.local
    ports:
      - name: postgres
        port: 5432
      - name: metrics
        port: 9187


