apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
  annotations:
    prometheus.io/port: '9187'
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: metrics
      port: 9187
      targetPort: 9187
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-prima
  namespace: default
  annotations:
    prometheus.io/port: '9187'
    prometheus.io/scheme: http
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
    - name: metrics
      port: 9187
      targetPort: 9187