apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "exampledb"

        - name: postgres-exporter
          image: wrouesnel/postgres_exporter
          ports:
            - name: metrics
              containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://admin:password@localhost:5432/exampledb?sslmode=disable"
