apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitoring
  annotations:
     argocd.argoproj.io/sync-wave: "3"
subjects:
- kind: ServiceAccount
  name: k8s-monitoring
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: monitoring
  apiGroup: rbac.authorization.k8s.io
