apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  annotations:
     argocd.argoproj.io/sync-wave: "1"
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s
      external_labels:
        cluster: kind
    scrape_configs:
    - job_name: prometheus
      static_configs:
      - targets: ["localhost:9090"]
    - job_name: kube-state-metrics
      static_configs:
      - targets: ["kube-state-metrics.monitoring.svc.local:8080"]
