apiVersion: v1
kind: Service
metadata:
  name: prometheus
  annotations:
     argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
      app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: prometheus
      name: prometheus