
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    name: applications
spec:
  project: default
  source:
    path: k8s-apps/argo-helm-apps
    repoURL: https://github.com/vicky1999s/kubernetes.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  info:
    - name: applications
      value: app of apps pattern
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
