apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base
  - namespace.yaml
  - application.yaml

patches:
 - path: resource-limits-patch.yaml
   target:
     kind: Deployment
 - path: resource-limits-patch.yaml
   target:
     kind: StatefulSet
