# Default values for argo-applications.
# This is a YAML-formatted file.

global:
  namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=true
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true

applications:
  monitoring:
    name: monitoring
    namespace: monitoring
    project: default
    source:
      repoURL: https://github.com/vicky1999s/kubernetes.git
      targetRevision: main
      path: k8s-apps/monitoring/overlay/dev-kind-cluster
    destination: https://kubernetes.default.svc
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  kube-state-metrics:
    name: kube-state-metrics
    namespace: monitoring
    project: default
    source:
      repoURL: https://github.com/vicky1999s/kubernetes.git
      targetRevision: main
      path: k8s-apps/kube-state-metrics/overlay/dev-kind-cluster
    destination: https://kubernetes.default.svc
    finalizers:
      - resources-finalizer.argocd.argoproj.io
  testing:
    name: testing
    namespace: default
    project: default
    source:
      repoURL: https://github.com/vicky1999s/kubernetes.git
      targetRevision: app-testing
      path: k8s-apps/testing/overlay/dev-kind-cluster
    destination: https://kubernetes.default.svc
    finalizers:
      - resources-finalizer.argocd.argoproj.io
